POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/meetings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODIyNzRhYjlhY2YwMTdlYzFkMDQ4YzAiLCJpYXQiOjE3NDcyNTgyNzIsImV4cCI6MTc0NzI2MTg3Mn0.Cmyt0i_7u-_JDdW06wvAu093PGaW-vnA_2DQMF5y7n0

{
  "title": "Перша зустріч",
  "description": "Тестова подія",
  "date": "2025-05-18T18:00:00.000Z"
}
